import os
import json
from datetime import datetime
from utils.banner import color


class ReportGenerator:
    def __init__(self, target, output_dir="reports"):
        self.target = target
        self.output_dir = output_dir
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        os.makedirs(output_dir, exist_ok=True)

    def generate(self, results):
        self._save_json(results)
        self._save_html(results)
        self._print_summary(results)

    def _save_json(self, results):
        path = os.path.join(self.output_dir, f"vulnscan_{self.timestamp}.json")
        report = {
            "target": self.target,
            "scan_time": self.timestamp,
            "total_modules": len(results),
            "vulnerabilities_found": sum(1 for r in results if r["result"].get("vulnerable")),
            "results": results,
        }
        with open(path, "w") as f:
            json.dump(report, f, indent=2)
        print(color(f"\n  [✓] JSON report saved: {path}", "green"))

    def _save_html(self, results):
        path = os.path.join(self.output_dir, f"vulnscan_{self.timestamp}.html")
        vulns = [r for r in results if r["result"].get("vulnerable")]
        clean = [r for r in results if not r["result"].get("vulnerable") and not r["result"].get("error")]
        errors = [r for r in results if r["result"].get("error")]

        rows = ""
        for r in results:
            res = r["result"]
            if res.get("vulnerable"):
                status = '<span class="badge vuln">VULNERABLE</span>'
                row_class = "vuln-row"
            elif res.get("error"):
                status = '<span class="badge error">ERROR</span>'
                row_class = "error-row"
            else:
                status = '<span class="badge clean">CLEAN</span>'
                row_class = "clean-row"

            findings_html = ""
            for f in res.get("findings", []):
                findings_html += f"<li>{f}</li>"

            rows += f"""
            <tr class="{row_class}">
                <td><code>{r['module']}</code></td>
                <td>{r['name']}</td>
                <td>{status}</td>
                <td>{res.get('summary', res.get('error', '—'))}</td>
                <td><ul>{findings_html}</ul></td>
            </tr>"""

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>VulnScan Report - {self.target}</title>
<style>
  body {{ font-family: 'Courier New', monospace; background: #0d1117; color: #c9d1d9; margin: 0; padding: 20px; }}
  h1 {{ color: #58a6ff; border-bottom: 1px solid #30363d; padding-bottom: 10px; }}
  .meta {{ color: #8b949e; font-size: 0.9em; margin-bottom: 20px; }}
  .summary {{ display: flex; gap: 20px; margin-bottom: 30px; }}
  .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 15px 25px; text-align: center; }}
  .card .num {{ font-size: 2em; font-weight: bold; }}
  .card.red .num {{ color: #f85149; }}
  .card.green .num {{ color: #3fb950; }}
  .card.grey .num {{ color: #8b949e; }}
  table {{ width: 100%; border-collapse: collapse; background: #161b22; border-radius: 8px; overflow: hidden; }}
  th {{ background: #21262d; color: #8b949e; text-align: left; padding: 10px 14px; font-size: 0.85em; text-transform: uppercase; }}
  td {{ padding: 10px 14px; border-top: 1px solid #21262d; vertical-align: top; font-size: 0.9em; }}
  .vuln-row td:first-child {{ border-left: 3px solid #f85149; }}
  .clean-row td:first-child {{ border-left: 3px solid #3fb950; }}
  .error-row td:first-child {{ border-left: 3px solid #d29922; }}
  .badge {{ padding: 3px 10px; border-radius: 4px; font-size: 0.8em; font-weight: bold; }}
  .badge.vuln {{ background: #3d1a1a; color: #f85149; }}
  .badge.clean {{ background: #1a3d1a; color: #3fb950; }}
  .badge.error {{ background: #3d2e0a; color: #d29922; }}
  ul {{ margin: 0; padding-left: 16px; color: #f0883e; }}
  code {{ background: #21262d; padding: 2px 6px; border-radius: 4px; color: #79c0ff; }}
</style>
</head>
<body>
<h1>🔍 VulnScan Report</h1>
<div class="meta">
  <strong>Target:</strong> {self.target} &nbsp;|&nbsp;
  <strong>Scan Time:</strong> {self.timestamp} &nbsp;|&nbsp;
  <strong>Modules Run:</strong> {len(results)}
</div>
<div class="summary">
  <div class="card red"><div class="num">{len(vulns)}</div>Vulnerable</div>
  <div class="card green"><div class="num">{len(clean)}</div>Clean</div>
  <div class="card grey"><div class="num">{len(errors)}</div>Errors</div>
</div>
<table>
<thead>
  <tr><th>Module</th><th>Name</th><th>Status</th><th>Summary</th><th>Findings</th></tr>
</thead>
<tbody>{rows}</tbody>
</table>
<p style="color:#30363d; font-size:0.75em; margin-top:30px;">
  ⚠ This report was generated by VulnScan. Only use on systems you own or have explicit permission to test.
</p>
</body>
</html>"""
        with open(path, "w") as f:
            f.write(html)
        print(color(f"  [✓] HTML report saved: {path}", "green"))

    def _print_summary(self, results):
        vulns = [r for r in results if r["result"].get("vulnerable")]
        print(color("\n  " + "═" * 60, "dim"))
        print(color("  SCAN COMPLETE — SUMMARY", "bold"))
        print(color("  " + "═" * 60, "dim"))
        print(f"  Target:     {color(self.target, 'cyan')}")
        print(f"  Modules:    {len(results)}")
        print(f"  Vulnerable: {color(str(len(vulns)), 'red') if vulns else color('0', 'green')}")
        if vulns:
            print(color("\n  ⚠  Vulnerabilities Found:", "red"))
            for r in vulns:
                print(f"     → {color(r['name'], 'yellow')}: {r['result'].get('summary','')}")
        print(color("  " + "═" * 60, "dim"))
        print()
